/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tkht2017;

import java.awt.CardLayout;
import java.awt.Container;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author Teemu
 */
public class ui extends javax.swing.JFrame {
    
    backEnd backEnd = new backEnd();
    
    public ui() {
        initComponents();       
    }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        panel1 = new javax.swing.JPanel();
        StartButton = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        NextButton = new javax.swing.JButton();
        Dlabel = new javax.swing.JLabel();
        scrollPane1 = new javax.swing.JScrollPane();
        textArea1 = new javax.swing.JTextArea();
        Alabel = new javax.swing.JLabel();
        scrollPane2 = new javax.swing.JScrollPane();
        textArea2 = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        Menu1 = new javax.swing.JMenu();
        MenuItem2 = new javax.swing.JMenuItem();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainPanel.setLayout(new java.awt.CardLayout());

        StartButton.setText("Start excercise set");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(242, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        mainPanel.add(panel1, "panel1");

        NextButton.setText("Next");
        NextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextButtonActionPerformed(evt);
            }
        });

        Dlabel.setText("Excercise description:");

        textArea1.setColumns(20);
        textArea1.setRows(5);
        scrollPane1.setViewportView(textArea1);
        textArea1.setEditable(false);

        Alabel.setText("Your answer:");

        textArea2.setColumns(20);
        textArea2.setRows(5);
        scrollPane2.setViewportView(textArea2);

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane1)
                    .addComponent(scrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel2Layout.createSequentialGroup()
                        .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Dlabel)
                            .addComponent(Alabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panel2Layout.createSequentialGroup()
                .addGap(282, 282, 282)
                .addComponent(NextButton)
                .addContainerGap(285, Short.MAX_VALUE))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Dlabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Alabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NextButton)
                .addContainerGap())
        );

        mainPanel.add(panel2, "panel2");

        Menu1.setText("Menu");

        MenuItem2.setText("Exit");
        MenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItem2ActionPerformed(evt);
            }
        });
        Menu1.add(MenuItem2);

        menuBar.add(Menu1);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItem2ActionPerformed
        backEnd.endSession();
        backEnd.endCon();
        dispose();
    }//GEN-LAST:event_MenuItem2ActionPerformed

    
    
    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        boolean jatketaan = backEnd.startCon();
         
        if (jatketaan) {
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.next(mainPanel);
            backEnd.initialize();
            
            if (backEnd.getError().isEmpty()) {
                JOptionPane.showMessageDialog(panel1,"Connection successful, good luck to the test!"); 
                textArea1.setText(backEnd.getExcerciseList().get(backEnd.currentExcercise()).getDescription());    
            }
            else {
                JOptionPane.showMessageDialog(panel1, backEnd.getError());
            }           
        } 
        else {
            JOptionPane.showMessageDialog(panel1, backEnd.getError());           
        }   
    }//GEN-LAST:event_StartButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        backEnd.endSession();;
        backEnd.endCon();
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void NextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextButtonActionPerformed
        String answer = textArea2.getText();
            if (answer.equals(backEnd.getExcerciseList().get(backEnd.currentExcercise()).example_answer)) {
                backEnd.nextExcercise();
                backEnd.endTry(answer);
                backEnd.startTry();
                backEnd.resetTry();
                textArea2.setText(""); 
                textArea1.setText(backEnd.getExcerciseList().get(backEnd.currentExcercise()).getDescription());

            }
            else {
                if (backEnd.currentTry() != 3) {
                    backEnd.endTry(answer);
                    backEnd.nextTry();
                    backEnd.startTry();
                    JOptionPane.showMessageDialog(panel1, "Wrong answer try again.");
                    textArea2.setText("");
                   }
                    
                else {               
                    if(backEnd.getExcerciseList().size() == backEnd.currentExcercise() + 1  && backEnd.currentTry() == 3 ) {
                        backEnd.endTry(answer);
                        backEnd.resetTry();
                        JOptionPane.showMessageDialog(panel1, "Test over closing program.");
                        dispose();
                    }
                    else {
                        backEnd.endTry(answer);
                        JOptionPane.showMessageDialog(panel1, "3rd wrong answer, moving to next question.");
                        backEnd.nextExcercise();
                        backEnd.resetTry();
                        backEnd.startTry();
                        textArea2.setText("");
                        textArea1.setText(backEnd.getExcerciseList().get(backEnd.currentExcercise()).getDescription()); 
                    }
                    }      
            } 
    }//GEN-LAST:event_NextButtonActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ui().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Alabel;
    private javax.swing.JLabel Dlabel;
    private javax.swing.JMenu Menu1;
    private javax.swing.JMenuItem MenuItem2;
    private javax.swing.JButton NextButton;
    private javax.swing.JButton StartButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JScrollPane scrollPane1;
    private javax.swing.JScrollPane scrollPane2;
    private javax.swing.JTextArea textArea1;
    private javax.swing.JTextArea textArea2;
    // End of variables declaration//GEN-END:variables
}
